[2024-08-22 19:14:36,168: INFO: main: Welcome to our custom log]
[2024-08-30 00:37:21,847: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 00:37:21,857: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 00:37:21,859: INFO: common: created directory at: artifacts]
[2024-08-30 00:37:21,860: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 00:37:21,862: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 00:37:34,232: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 16:07:59,579: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 16:07:59,579: ERROR: main: 'ConfigurationManager' object has no attribute 'config']
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    data_ingestion.main()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\config\configuration.py", line 82, in get_data_ingestion_config
    config = self.config.data_ingestion
AttributeError: 'ConfigurationManager' object has no attribute 'config'
[2024-09-12 16:17:55,594: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 16:17:55,595: ERROR: main: 'ConfigurationManager' object has no attribute 'config']
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    data_ingestion.main()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\config\configuration.py", line 73, in get_data_ingestion_config
    config = self.config.data_ingestion
AttributeError: 'ConfigurationManager' object has no attribute 'config'
[2024-09-12 16:20:18,560: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 16:20:18,565: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 16:20:18,576: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 16:20:18,576: INFO: common: created directory at: artifacts]
[2024-09-12 16:20:18,578: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 16:20:18,579: ERROR: main: DataIngestion() takes no arguments]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    data_ingestion.main()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion = DataIngestion(config=data_ingestion_config)
TypeError: DataIngestion() takes no arguments
[2024-09-12 16:21:18,193: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 16:21:18,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 16:21:18,196: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 16:21:18,197: INFO: common: created directory at: artifacts]
[2024-09-12 16:21:18,198: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 16:21:18,198: ERROR: main: DataIngestion() takes no arguments]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    data_ingestion.main()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion = DataIngestion(config=data_ingestion_config)
TypeError: DataIngestion() takes no arguments
[2024-09-12 16:22:22,129: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 16:22:22,135: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 16:22:22,137: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 16:22:22,138: INFO: common: created directory at: artifacts]
[2024-09-12 16:22:22,140: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 16:22:22,141: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 16:22:34,264: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 16:22:35,137: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 16:27:56,409: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 16:27:56,411: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 16:27:56,412: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 16:27:56,413: INFO: common: created directory at: artifacts]
[2024-09-12 16:27:56,414: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 16:27:56,415: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 16:28:09,255: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 16:28:09,757: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 17:03:20,314: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:03:20,317: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:03:20,320: INFO: common: created directory at: artifacts]
[2024-09-12 17:03:20,322: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 17:10:33,568: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:10:33,579: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:10:33,583: INFO: common: created directory at: artifacts]
[2024-09-12 17:10:33,585: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 17:10:46,465: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-12 17:20:30,006: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 17:20:30,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:20:30,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:20:30,014: INFO: common: created directory at: artifacts]
[2024-09-12 17:20:30,015: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 17:20:30,016: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 17:20:42,140: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 17:20:42,776: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 17:24:16,899: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 17:24:16,901: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:24:16,903: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:24:16,903: INFO: common: created directory at: artifacts]
[2024-09-12 17:24:16,904: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 17:24:16,904: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 17:24:29,099: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 17:24:29,615: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 17:24:29,615: INFO: main: *]
[2024-09-12 17:24:29,615: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-12 17:24:29,619: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:24:29,621: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:24:29,621: INFO: common: created directory at: artifacts]
[2024-09-12 17:24:29,622: ERROR: main: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    prepare_base_model.main()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 15, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2024-09-12 17:30:24,378: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 17:30:24,378: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:30:24,378: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:30:24,378: INFO: common: created directory at: artifacts]
[2024-09-12 17:30:24,378: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 17:30:24,387: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 17:30:36,448: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 17:30:36,972: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 17:30:36,972: INFO: main: *]
[2024-09-12 17:30:36,977: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-12 17:30:36,980: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:30:36,982: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:30:36,983: INFO: common: created directory at: artifacts]
[2024-09-12 17:30:36,983: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 17:30:37,502: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-12 17:30:37,918: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-12 17:36:49,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:36:49,688: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:36:49,690: INFO: common: created directory at: artifacts]
[2024-09-12 17:36:49,693: INFO: common: created directory at: artifacts\training]
[2024-09-12 17:40:23,171: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:40:23,177: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:40:23,180: INFO: common: created directory at: artifacts]
[2024-09-12 17:40:23,183: INFO: common: created directory at: artifacts\training]
[2024-09-12 17:46:10,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:46:10,603: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:46:10,607: INFO: common: created directory at: artifacts]
[2024-09-12 17:46:10,609: INFO: common: created directory at: artifacts\training]
[2024-09-12 17:47:43,379: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 17:47:43,385: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 17:47:43,388: INFO: common: created directory at: artifacts]
[2024-09-12 17:47:43,392: INFO: common: created directory at: artifacts\training]
[2024-09-12 18:00:42,927: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 18:00:42,930: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:00:42,932: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:00:42,933: INFO: common: created directory at: artifacts]
[2024-09-12 18:00:42,933: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 18:00:42,933: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:00:55,349: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:00:55,847: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 18:00:55,848: INFO: main: *]
[2024-09-12 18:00:55,848: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-12 18:00:55,851: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:00:55,854: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:00:55,855: INFO: common: created directory at: artifacts]
[2024-09-12 18:00:55,855: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 18:00:56,342: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-12 18:00:56,931: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-12 18:00:56,932: INFO: main: *]
[2024-09-12 18:00:56,933: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-12 18:00:56,936: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:00:56,939: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:00:56,939: INFO: common: created directory at: artifacts]
[2024-09-12 18:00:56,940: INFO: common: created directory at: artifacts\training]
[2024-09-12 18:01:43,897: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-12 18:04:24,874: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 18:04:24,874: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:04:24,878: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:04:24,878: INFO: common: created directory at: artifacts]
[2024-09-12 18:04:24,879: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 18:04:24,879: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:04:37,559: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:04:38,105: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 18:04:38,105: INFO: main: *]
[2024-09-12 18:04:38,105: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-12 18:04:38,108: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:04:38,110: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:04:38,111: INFO: common: created directory at: artifacts]
[2024-09-12 18:04:38,112: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 18:04:38,628: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-12 18:04:38,981: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-12 18:04:38,981: INFO: main: *]
[2024-09-12 18:04:38,981: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-12 18:04:38,986: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:04:38,989: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:04:38,990: INFO: common: created directory at: artifacts]
[2024-09-12 18:04:38,991: INFO: common: created directory at: artifacts\training]
[2024-09-12 18:04:39,458: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 37, in <module>
    model_trainer.main()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_03_model_training.py", line 20, in main
    training.train_valid_generator()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\components\model_training.py", line 37, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2024-09-12 18:09:37,845: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:09:37,852: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:09:37,855: INFO: common: created directory at: artifacts]
[2024-09-12 18:09:37,857: INFO: common: created directory at: artifacts\training]
[2024-09-12 18:10:07,136: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:10:07,142: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:10:07,145: INFO: common: created directory at: artifacts]
[2024-09-12 18:10:07,146: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 18:10:07,149: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:10:19,960: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:10:33,484: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:10:33,489: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:10:33,491: INFO: common: created directory at: artifacts]
[2024-09-12 18:10:33,493: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 18:10:34,196: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-12 18:12:51,381: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 18:12:51,385: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:12:51,387: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:12:51,388: INFO: common: created directory at: artifacts]
[2024-09-12 18:12:51,388: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 18:12:51,389: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:13:03,925: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:13:04,549: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 18:13:04,552: INFO: main: *]
[2024-09-12 18:13:04,553: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-12 18:13:04,558: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:13:04,562: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:13:04,565: INFO: common: created directory at: artifacts]
[2024-09-12 18:13:04,566: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 18:13:05,430: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-12 18:13:05,880: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-12 18:13:05,881: INFO: main: *]
[2024-09-12 18:13:05,881: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-12 18:13:05,884: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:13:05,886: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:13:05,886: INFO: common: created directory at: artifacts]
[2024-09-12 18:13:05,887: INFO: common: created directory at: artifacts\training]
[2024-09-12 18:14:00,333: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-12 18:19:05,658: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 18:19:05,669: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:19:05,669: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:19:05,669: INFO: common: created directory at: artifacts]
[2024-09-12 18:19:05,669: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 18:19:05,669: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:19:17,976: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:19:18,517: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 18:19:18,518: INFO: main: *]
[2024-09-12 18:19:18,518: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-12 18:19:18,521: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:19:18,523: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:19:18,524: INFO: common: created directory at: artifacts]
[2024-09-12 18:19:18,525: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 18:19:19,093: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-12 18:19:19,443: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-12 18:19:19,443: INFO: main: *]
[2024-09-12 18:19:19,443: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-12 18:19:19,447: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:19:19,449: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:19:19,450: INFO: common: created directory at: artifacts]
[2024-09-12 18:19:19,451: INFO: common: created directory at: artifacts\training]
[2024-09-12 18:20:05,679: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-12 18:34:50,921: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:34:50,932: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:34:50,933: INFO: common: created directory at: artifacts]
[2024-09-12 18:34:50,935: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 18:34:50,935: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:35:09,184: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 18:36:18,545: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:36:18,549: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:36:18,551: INFO: common: created directory at: artifacts]
[2024-09-12 18:36:18,553: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 18:36:19,282: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-12 18:36:33,072: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:36:33,077: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:36:33,078: INFO: common: created directory at: artifacts]
[2024-09-12 18:36:33,080: INFO: common: created directory at: artifacts\training]
[2024-09-12 18:37:49,637: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:37:49,647: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:37:49,650: INFO: common: created directory at: artifacts]
[2024-09-12 18:39:02,987: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 18:39:02,991: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 18:39:02,993: INFO: common: created directory at: artifacts]
[2024-09-12 18:39:17,129: INFO: common: json file saved at: scores.json]
[2024-09-12 18:39:20,382: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-12 18:39:21,025: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmpoinruck3\model\data\model\assets]
[2024-09-12 19:22:15,259: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 19:22:15,266: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 19:22:15,269: INFO: common: created directory at: artifacts]
[2024-09-12 19:22:28,605: INFO: common: json file saved at: scores.json]
[2024-09-12 19:22:32,721: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-12 19:22:33,636: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmp9pmm5oin\model\data\model\assets]
[2024-09-12 19:24:16,456: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 19:24:16,462: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 19:24:16,465: INFO: common: created directory at: artifacts]
[2024-09-12 19:24:30,098: INFO: common: json file saved at: scores.json]
[2024-09-12 19:24:33,842: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-12 19:24:34,556: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmp98j7km31\model\data\model\assets]
[2024-09-12 19:46:40,868: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 19:46:40,875: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 19:46:40,876: INFO: common: created directory at: artifacts]
[2024-09-12 19:46:58,489: INFO: common: json file saved at: scores.json]
[2024-09-12 19:47:02,135: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-12 19:47:02,877: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmp9smyhclv\model\data\model\assets]
[2024-09-12 20:02:27,438: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 20:02:27,448: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 20:02:27,454: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 20:02:27,456: INFO: common: created directory at: artifacts]
[2024-09-12 20:02:27,457: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 20:02:27,459: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 20:02:58,531: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 20:02:59,422: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 20:02:59,422: INFO: main: *]
[2024-09-12 20:02:59,422: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-12 20:02:59,425: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 20:02:59,426: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 20:02:59,427: INFO: common: created directory at: artifacts]
[2024-09-12 20:02:59,428: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 20:03:00,043: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-12 20:03:00,423: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-12 20:03:00,423: INFO: main: *]
[2024-09-12 20:03:00,424: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-12 20:03:00,427: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 20:03:00,429: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 20:03:00,430: INFO: common: created directory at: artifacts]
[2024-09-12 20:03:00,430: INFO: common: created directory at: artifacts\training]
[2024-09-12 20:03:46,268: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-12 20:03:46,269: INFO: main: *]
[2024-09-12 20:03:46,269: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-12 20:03:46,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 20:03:46,275: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 20:03:46,276: INFO: common: created directory at: artifacts]
[2024-09-12 20:03:46,277: ERROR: main: Evaluation() takes no arguments]
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 17, in main
    evaluation = Evaluation(eval_config)
TypeError: Evaluation() takes no arguments
[2024-09-12 20:06:12,988: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-12 20:06:12,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 20:06:12,993: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 20:06:12,993: INFO: common: created directory at: artifacts]
[2024-09-12 20:06:12,994: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-12 20:06:12,994: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 20:06:30,075: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-12 20:06:30,625: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-12 20:06:30,625: INFO: main: *]
[2024-09-12 20:06:30,625: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-12 20:06:30,628: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 20:06:30,630: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 20:06:30,630: INFO: common: created directory at: artifacts]
[2024-09-12 20:06:30,631: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-12 20:06:31,074: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-12 20:06:31,410: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-12 20:06:31,411: INFO: main: *]
[2024-09-12 20:06:31,411: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-12 20:06:31,414: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 20:06:31,416: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 20:06:31,417: INFO: common: created directory at: artifacts]
[2024-09-12 20:06:31,418: INFO: common: created directory at: artifacts\training]
[2024-09-12 20:07:13,539: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-12 20:07:13,539: INFO: main: *]
[2024-09-12 20:07:13,539: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-12 20:07:13,545: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-12 20:07:13,547: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-12 20:07:13,548: INFO: common: created directory at: artifacts]
[2024-09-12 20:07:27,066: INFO: common: json file saved at: scores.json]
[2024-09-12 20:07:27,068: INFO: common: json file saved at: scores.json]
[2024-09-12 20:07:27,068: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 15:16:05,056: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-13 15:16:05,067: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:16:05,074: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:16:05,075: INFO: common: created directory at: artifacts]
[2024-09-13 15:16:05,075: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-13 15:16:05,076: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:16:17,512: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:16:18,074: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-13 15:16:18,074: INFO: main: *]
[2024-09-13 15:16:18,074: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-13 15:16:18,078: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:16:18,080: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:16:18,081: INFO: common: created directory at: artifacts]
[2024-09-13 15:16:18,082: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-13 15:16:18,772: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-13 15:16:19,128: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-13 15:16:19,130: INFO: main: *]
[2024-09-13 15:16:19,130: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-13 15:16:19,134: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:16:19,136: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:16:19,137: INFO: common: created directory at: artifacts]
[2024-09-13 15:16:19,138: INFO: common: created directory at: artifacts\training]
[2024-09-13 15:17:40,566: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-13 15:17:40,566: INFO: main: *]
[2024-09-13 15:17:40,566: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 15:17:40,570: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:17:40,572: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:17:40,573: INFO: common: created directory at: artifacts]
[2024-09-13 15:17:53,431: INFO: common: json file saved at: scores.json]
[2024-09-13 15:17:53,432: INFO: common: json file saved at: scores.json]
[2024-09-13 15:17:53,433: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 15:20:34,227: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-13 15:20:34,234: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:20:34,237: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:20:34,238: INFO: common: created directory at: artifacts]
[2024-09-13 15:20:34,239: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-13 15:20:34,240: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:20:46,566: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:20:47,167: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-13 15:20:47,168: INFO: main: *]
[2024-09-13 15:20:47,168: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-13 15:20:47,174: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:20:47,178: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:20:47,179: INFO: common: created directory at: artifacts]
[2024-09-13 15:20:47,180: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-13 15:20:47,749: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-13 15:20:48,174: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-13 15:20:48,174: INFO: main: *]
[2024-09-13 15:20:48,176: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-13 15:20:48,179: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:20:48,182: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:20:48,183: INFO: common: created directory at: artifacts]
[2024-09-13 15:20:48,184: INFO: common: created directory at: artifacts\training]
[2024-09-13 15:22:23,233: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-13 15:22:23,234: INFO: main: *]
[2024-09-13 15:22:23,234: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 15:22:23,239: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:22:23,241: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:22:23,242: INFO: common: created directory at: artifacts]
[2024-09-13 15:22:37,248: INFO: common: json file saved at: scores.json]
[2024-09-13 15:22:37,250: INFO: common: json file saved at: scores.json]
[2024-09-13 15:22:37,250: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 15:25:28,013: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-13 15:25:28,017: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:25:28,018: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:25:28,019: INFO: common: created directory at: artifacts]
[2024-09-13 15:25:28,019: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-13 15:25:28,020: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:25:40,050: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:25:40,536: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-13 15:25:40,536: INFO: main: *]
[2024-09-13 15:25:40,536: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-13 15:25:40,544: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:25:40,546: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:25:40,547: INFO: common: created directory at: artifacts]
[2024-09-13 15:25:40,547: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-13 15:25:40,937: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-13 15:25:41,372: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-13 15:25:41,373: INFO: main: *]
[2024-09-13 15:25:41,373: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-13 15:25:41,378: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:25:41,382: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:25:41,383: INFO: common: created directory at: artifacts]
[2024-09-13 15:25:41,384: INFO: common: created directory at: artifacts\training]
[2024-09-13 15:27:03,326: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-13 15:27:03,327: INFO: main: *]
[2024-09-13 15:27:03,327: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 15:27:03,330: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:27:03,333: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:27:03,333: INFO: common: created directory at: artifacts]
[2024-09-13 15:27:17,674: INFO: common: json file saved at: scores.json]
[2024-09-13 15:27:17,675: INFO: common: json file saved at: scores.json]
[2024-09-13 15:27:17,676: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 15:27:58,636: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-13 15:27:58,641: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:27:58,644: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:27:58,647: INFO: common: created directory at: artifacts]
[2024-09-13 15:27:58,649: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-13 15:27:58,650: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:28:10,598: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:28:11,187: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-13 15:28:11,187: INFO: main: *]
[2024-09-13 15:28:11,187: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-13 15:28:11,194: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:28:11,195: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:28:11,196: INFO: common: created directory at: artifacts]
[2024-09-13 15:28:11,196: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-13 15:28:11,626: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-13 15:28:11,917: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-13 15:28:11,917: INFO: main: *]
[2024-09-13 15:28:11,917: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-13 15:28:11,921: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:28:11,924: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:28:11,924: INFO: common: created directory at: artifacts]
[2024-09-13 15:28:11,926: INFO: common: created directory at: artifacts\training]
[2024-09-13 15:29:40,336: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-13 15:29:40,337: INFO: main: *]
[2024-09-13 15:29:40,337: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 15:29:40,342: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:29:40,345: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:29:40,345: INFO: common: created directory at: artifacts]
[2024-09-13 15:29:54,739: INFO: common: json file saved at: scores.json]
[2024-09-13 15:29:54,740: INFO: common: json file saved at: scores.json]
[2024-09-13 15:29:56,727: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-13 15:29:57,428: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmpsvmklcqc\model\data\model\assets]
[2024-09-13 15:30:07,651: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\51edbc4b8ecc412ab41445494869f92c\artifacts\model\data]
[2024-09-13 15:30:07,653: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\51edbc4b8ecc412ab41445494869f92c\artifacts\model\data\model]
[2024-09-13 15:30:07,654: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\51edbc4b8ecc412ab41445494869f92c\artifacts\model\data\model\assets]
[2024-09-13 15:30:07,659: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\51edbc4b8ecc412ab41445494869f92c\artifacts\model\data\model\variables]
[2024-09-13 15:30:07,806: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 15:39:19,558: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-13 15:39:19,561: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:39:19,564: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:39:19,566: INFO: common: created directory at: artifacts]
[2024-09-13 15:39:19,567: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-13 15:39:19,567: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:39:32,334: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:39:32,812: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-13 15:39:32,812: INFO: main: *]
[2024-09-13 15:39:32,812: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-13 15:39:32,815: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:39:32,817: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:39:32,818: INFO: common: created directory at: artifacts]
[2024-09-13 15:39:32,819: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-13 15:39:33,469: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-13 15:39:33,846: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-13 15:39:33,846: INFO: main: *]
[2024-09-13 15:39:33,847: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-13 15:39:33,850: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:39:33,852: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:39:33,853: INFO: common: created directory at: artifacts]
[2024-09-13 15:39:33,854: INFO: common: created directory at: artifacts\training]
[2024-09-13 15:41:03,194: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-13 15:41:03,195: INFO: main: *]
[2024-09-13 15:41:03,195: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 15:41:03,199: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:41:03,202: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:41:03,203: INFO: common: created directory at: artifacts]
[2024-09-13 15:41:17,418: INFO: common: json file saved at: scores.json]
[2024-09-13 15:41:17,419: INFO: common: json file saved at: scores.json]
[2024-09-13 15:41:19,188: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-13 15:41:19,852: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmp_b6mzblh\model\data\model\assets]
[2024-09-13 15:41:28,817: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\6771fe874e6b43a3b2c09ee96b357641\artifacts\model\data]
[2024-09-13 15:41:28,818: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\6771fe874e6b43a3b2c09ee96b357641\artifacts\model\data\model]
[2024-09-13 15:41:28,819: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\6771fe874e6b43a3b2c09ee96b357641\artifacts\model\data\model\assets]
[2024-09-13 15:41:28,823: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\6771fe874e6b43a3b2c09ee96b357641\artifacts\model\data\model\variables]
[2024-09-13 15:41:28,946: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 15:42:55,127: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:42:55,132: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:42:55,133: INFO: common: created directory at: artifacts]
[2024-09-13 15:43:12,675: INFO: common: json file saved at: scores.json]
[2024-09-13 15:43:16,697: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-13 15:43:17,886: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmp_pxqyr8j\model\data\model\assets]
[2024-09-13 15:47:29,626: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-13 15:47:29,627: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:47:29,627: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:47:29,627: INFO: common: created directory at: artifacts]
[2024-09-13 15:47:29,627: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-13 15:47:29,627: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:47:41,608: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:47:42,101: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-13 15:47:42,101: INFO: main: *]
[2024-09-13 15:47:42,101: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-13 15:47:42,105: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:47:42,107: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:47:42,107: INFO: common: created directory at: artifacts]
[2024-09-13 15:47:42,107: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-13 15:47:42,631: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-13 15:47:42,967: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-13 15:47:42,967: INFO: main: *]
[2024-09-13 15:47:42,967: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-13 15:47:42,973: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:47:42,975: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:47:42,976: INFO: common: created directory at: artifacts]
[2024-09-13 15:47:42,977: INFO: common: created directory at: artifacts\training]
[2024-09-13 15:49:12,468: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-13 15:49:12,469: INFO: main: *]
[2024-09-13 15:49:12,469: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 15:49:12,473: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:49:12,476: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:49:12,477: INFO: common: created directory at: artifacts]
[2024-09-13 15:49:26,157: INFO: common: json file saved at: scores.json]
[2024-09-13 15:49:26,158: INFO: common: json file saved at: scores.json]
[2024-09-13 15:49:27,953: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-13 15:49:29,005: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmpe_4dxsgk\model\data\model\assets]
[2024-09-13 15:49:40,332: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\5e4d7e3d0d70414bb6d0fbc5ccdb0247\artifacts\model\data]
[2024-09-13 15:49:40,334: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\5e4d7e3d0d70414bb6d0fbc5ccdb0247\artifacts\model\data\model]
[2024-09-13 15:49:40,336: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\5e4d7e3d0d70414bb6d0fbc5ccdb0247\artifacts\model\data\model\assets]
[2024-09-13 15:49:40,339: INFO: dir_util: creating C:\Users\BHAVYA\Desktop\Kidney disease Clasification\Kidney-Disease-Classification-MLflow-DVC\mlruns\0\5e4d7e3d0d70414bb6d0fbc5ccdb0247\artifacts\model\data\model\variables]
[2024-09-13 15:49:40,467: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 15:56:29,328: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-13 15:56:29,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:56:29,333: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:56:29,334: INFO: common: created directory at: artifacts]
[2024-09-13 15:56:29,335: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-13 15:56:29,336: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:56:41,148: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 15:56:41,826: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-13 15:56:41,827: INFO: main: *]
[2024-09-13 15:56:41,827: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-13 15:56:41,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:56:41,835: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:56:41,836: INFO: common: created directory at: artifacts]
[2024-09-13 15:56:41,837: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-13 15:56:42,526: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-13 15:56:42,961: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-13 15:56:42,961: INFO: main: *]
[2024-09-13 15:56:42,961: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-13 15:56:42,966: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:56:42,968: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:56:42,968: INFO: common: created directory at: artifacts]
[2024-09-13 15:56:42,969: INFO: common: created directory at: artifacts\training]
[2024-09-13 15:58:15,396: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-13 15:58:15,396: INFO: main: *]
[2024-09-13 15:58:15,397: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 15:58:15,402: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 15:58:15,405: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 15:58:15,407: INFO: common: created directory at: artifacts]
[2024-09-13 15:58:32,217: INFO: common: json file saved at: scores.json]
[2024-09-13 15:58:32,220: INFO: common: json file saved at: scores.json]
[2024-09-13 15:58:36,415: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-13 15:58:37,209: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmpp3pi1yut\model\data\model\assets]
[2024-09-13 15:59:10,418: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 16:00:01,477: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-13 16:00:01,484: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:00:01,491: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:00:01,494: INFO: common: created directory at: artifacts]
[2024-09-13 16:00:01,499: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-13 16:00:01,501: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 16:00:13,633: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 16:00:14,346: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-13 16:00:14,347: INFO: main: *]
[2024-09-13 16:00:14,347: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-13 16:00:14,351: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:00:14,353: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:00:14,354: INFO: common: created directory at: artifacts]
[2024-09-13 16:00:14,354: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-13 16:00:15,003: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-13 16:00:15,394: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-13 16:00:15,395: INFO: main: *]
[2024-09-13 16:00:15,395: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-13 16:00:15,399: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:00:15,401: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:00:15,402: INFO: common: created directory at: artifacts]
[2024-09-13 16:00:15,403: INFO: common: created directory at: artifacts\training]
[2024-09-13 16:02:11,272: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-13 16:02:11,276: INFO: main: *]
[2024-09-13 16:02:11,276: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 16:02:11,286: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:02:11,291: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:02:11,294: INFO: common: created directory at: artifacts]
[2024-09-13 16:02:27,954: INFO: common: json file saved at: scores.json]
[2024-09-13 16:02:27,956: INFO: common: json file saved at: scores.json]
[2024-09-13 16:02:31,585: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-13 16:02:32,300: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmpz6rm0l5d\model\data\model\assets]
[2024-09-13 16:03:05,778: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 16:04:42,515: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-13 16:04:42,518: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:04:42,520: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:04:42,521: INFO: common: created directory at: artifacts]
[2024-09-13 16:04:42,522: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-13 16:04:42,522: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 16:04:54,610: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 16:04:55,152: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-13 16:04:55,152: INFO: main: *]
[2024-09-13 16:04:55,152: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-13 16:04:55,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:04:55,158: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:04:55,158: INFO: common: created directory at: artifacts]
[2024-09-13 16:04:55,159: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-13 16:04:55,829: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-13 16:04:56,356: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-13 16:04:56,356: INFO: main: *]
[2024-09-13 16:04:56,357: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-09-13 16:04:56,361: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:04:56,364: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:04:56,366: INFO: common: created directory at: artifacts]
[2024-09-13 16:04:56,366: INFO: common: created directory at: artifacts\training]
[2024-09-13 16:06:53,848: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-13 16:06:53,852: INFO: main: *]
[2024-09-13 16:06:53,853: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 16:06:53,859: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:06:53,863: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:06:53,865: INFO: common: created directory at: artifacts]
[2024-09-13 16:07:11,798: INFO: common: json file saved at: scores.json]
[2024-09-13 16:07:11,800: INFO: common: json file saved at: scores.json]
[2024-09-13 16:07:16,273: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-13 16:07:17,078: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmppx2ii04c\model\data\model\assets]
[2024-09-13 16:07:55,143: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 16:27:32,394: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-09-13 16:27:32,396: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:27:32,396: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:27:32,396: INFO: common: created directory at: artifacts]
[2024-09-13 16:27:32,396: INFO: common: created directory at: artifacts/data_ingestion]
[2024-09-13 16:27:32,396: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 16:27:44,515: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/13mRYuUPCc4glFqrvLThrxC1zAy5dlHKO/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-09-13 16:27:45,309: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-09-13 16:28:02,354: INFO: stage_02_prepare_base_model: *]
[2024-09-13 16:28:02,354: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-09-13 16:28:02,357: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:28:02,359: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:28:02,359: INFO: common: created directory at: artifacts]
[2024-09-13 16:28:02,360: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-09-13 16:28:02,933: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-09-13 16:28:03,296: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-09-13 16:31:43,356: INFO: stage_03_model_training: *]
[2024-09-13 16:31:43,356: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-09-13 16:31:43,368: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:31:43,371: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:31:43,371: INFO: common: created directory at: artifacts]
[2024-09-13 16:31:43,372: INFO: common: created directory at: artifacts\training]
[2024-09-13 16:33:07,779: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-09-13 16:33:15,806: INFO: stage_04_model_evaluation: *******************]
[2024-09-13 16:33:15,806: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 16:33:15,808: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:33:15,810: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:33:15,810: INFO: common: created directory at: artifacts]
[2024-09-13 16:33:29,126: INFO: common: json file saved at: scores.json]
[2024-09-13 16:33:29,127: INFO: common: json file saved at: scores.json]
[2024-09-13 16:33:29,128: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 16:53:41,348: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 16:53:41,348: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 16:53:50,696: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 16:53:50] "GET / HTTP/1.1" 200 -]
[2024-09-13 16:53:57,326: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-09-13 16:53:57,341: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 16:53:57] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-13 16:55:50,068: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 16:55:50,069: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 16:55:52,301: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 16:55:52] "GET / HTTP/1.1" 200 -]
[2024-09-13 16:56:09,524: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-09-13 16:56:09,534: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 16:56:09] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-13 16:56:49,298: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 16:56:49] "GET / HTTP/1.1" 200 -]
[2024-09-13 16:57:10,297: INFO: stage_04_model_evaluation: *******************]
[2024-09-13 16:57:10,297: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-09-13 16:57:10,306: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-09-13 16:57:10,308: INFO: common: yaml file: params.yaml loaded successfully]
[2024-09-13 16:57:10,308: INFO: common: created directory at: artifacts]
[2024-09-13 16:57:20,845: INFO: common: json file saved at: scores.json]
[2024-09-13 16:57:20,846: INFO: common: json file saved at: scores.json]
[2024-09-13 16:57:24,208: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-09-13 16:57:24,877: INFO: builder_impl: Assets written to: C:\Users\BHAVYA\AppData\Local\Temp\tmpmryl3grp\model\data\model\assets]
[2024-09-13 16:58:01,144: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-09-13 16:59:26,271: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 16:59:26,272: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 16:59:30,507: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 16:59:30] "GET / HTTP/1.1" 200 -]
[2024-09-13 16:59:36,393: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-09-13 16:59:36,405: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 16:59:36] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-13 17:09:09,248: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 17:09:09,249: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 17:09:24,949: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:09:24] "GET / HTTP/1.1" 200 -]
[2024-09-13 17:09:40,000: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-09-13 17:09:40,010: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:09:40] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-13 17:10:45,821: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 17:10:45,821: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 17:10:49,501: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:10:49] "GET / HTTP/1.1" 200 -]
[2024-09-13 17:10:53,339: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:10:53] "GET / HTTP/1.1" 200 -]
[2024-09-13 17:11:14,700: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-09-13 17:11:14,709: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:11:14] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-13 17:16:26,275: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 17:16:26,276: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 17:16:29,344: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:16:29] "GET / HTTP/1.1" 200 -]
[2024-09-13 17:16:33,550: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 17, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-09-13 17:16:33,560: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:16:33] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-13 17:19:55,700: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 17:19:55,701: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 17:19:55,814: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:19:55] "GET / HTTP/1.1" 200 -]
[2024-09-13 17:19:59,091: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:19:59] "GET / HTTP/1.1" 200 -]
[2024-09-13 17:20:04,930: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:20:04] "POST /predict HTTP/1.1" 200 -]
[2024-09-13 17:21:40,691: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 17:21:40,692: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 17:21:40,762: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:21:40] "GET / HTTP/1.1" 200 -]
[2024-09-13 17:21:42,577: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:21:42] "GET / HTTP/1.1" 200 -]
[2024-09-13 17:21:48,310: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("training", "model.h5"))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at training\model.h5
[2024-09-13 17:21:48,324: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:21:48] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-13 17:22:44,107: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 17:22:44,107: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 17:22:44,476: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:22:44] "GET / HTTP/1.1" 200 -]
[2024-09-13 17:22:49,977: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\bhavya\desktop\kidney disease clasification\kidney-disease-classification-mlflow-dvc\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("artifacts\training", "model.h5"))
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\ProgramData\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at artifacts	raining\model.h5
[2024-09-13 17:22:49,986: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:22:49] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-09-13 17:23:22,026: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 17:23:22,028: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 17:23:22,234: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:23:22] "GET / HTTP/1.1" 200 -]
[2024-09-13 17:23:27,133: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:23:27] "POST /predict HTTP/1.1" 200 -]
[2024-09-13 17:23:38,440: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:23:38] "POST /predict HTTP/1.1" 200 -]
[2024-09-13 17:23:47,414: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:23:47] "POST /predict HTTP/1.1" 200 -]
[2024-09-13 17:23:57,161: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:23:57] "POST /predict HTTP/1.1" 200 -]
[2024-09-13 17:24:04,648: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000027F5CA13EE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-09-13 17:24:04,654: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:24:04] "POST /predict HTTP/1.1" 200 -]
[2024-09-13 17:24:15,209: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000027F5CA13C10> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-09-13 17:24:15,220: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 17:24:15] "POST /predict HTTP/1.1" 200 -]
[2024-09-13 19:25:21,741: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.6:8080]
[2024-09-13 19:25:21,746: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-09-13 19:25:33,967: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 19:25:33] "GET / HTTP/1.1" 200 -]
[2024-09-13 19:25:36,137: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 19:25:36] "GET / HTTP/1.1" 200 -]
[2024-09-13 19:25:42,352: INFO: _internal: 127.0.0.1 - - [13/Sep/2024 19:25:42] "POST /predict HTTP/1.1" 200 -]
